apiVersion: v1
kind: Service
metadata:
  name: gowebapp-mysql
  # namespace: database
  labels:
    run: gowebapp-mysql
    tier: backend
spec:
  type: ClusterIP
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    run: gowebapp-mysql
    tier: backend
---
apiVersion: apps/v1
kind: deployment
metadata: 
  name: gowebapp-mysql
  # namespace: database
  labels:
    run: gowebapp-mysql
    tier: backend
spec:
  replicas: 1
  strategy:
    type: recreate
  selector:
    matchLabels:
      run: gowebapp-mysql
      tier: backend
  template:
    metadata:
      labels:
        run: gowebapp-mysql
        tier: backend
    spec:
      containers:
      - name: gowebapp-mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: heptio
        image: localhost:5000/gowebapp-mysql:v1 
        ports:
          - name: dbcoms
            containerPort: 3306
            protocol: TCP
