apiVersion: v1
kind: Service
metadata:
  name: gowebapp
  # namespace: frontend
  labels:
    run: gowebapp
    tier: frontend
spec:
  type: ClusterIP
  ports:
    port: 9000
    targetPort: 80
  selector:
    run: gowebapp
    tier: frontend
---
apiVersion: apps/v1
kind: deployment
metadata:
  name: gowebapp
  labels:
    run: gowebapp
    tier: frontend
spec:
  replica: 2
  selector:
    matchLabels:
      run: gowebapp
      tier: frontend
  template:
    metadata:
      labels:
        run: gowebapp
        tier: frontend
    spec:
      containers:
      - name: gowebapp
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: heptio
        image: localhost:5000/gowebapp:v1      
        ports:
          - name: webout
            containerPort: 80
            protocol: TCP
