apiVersion: v1
kind: Service
metadata:
  name: gowebapp
  # namespace: frontend
  labels:
    run: gowebapp
    tier: frontend
spec:
  type: NodePort
  ports:
    - port: 9000
      targetPort: 80
  selector:
    run: gowebapp
    tier: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gowebapp
  # namespace: frontend
  labels:
    run: gowebapp
    tier: frontend
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      run: gowebapp
      tier: frontend
  template:
    metadata:
      labels:
        run: gowebapp
        tier: frontend
    spec:
      containers:
        - name: gowebapp
          env:
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: dbpass
                key: dbpass
          image: localhost:5000/gowebapp:v2
          volumeMounts:
            - mountPath: "/tmp/site/config/"
              subPath: "config.json"
              name: "frontend-config"
          ports:
            - name: webout
              containerPort: 80
              protocol: TCP
      volumes:
        - name: "frontend-config"
          configMap:
            name: "frontend-config"
